// ============================================
// FlowForge — Workflow Executor (BullMQ Worker)
// ============================================
// This is the engine that runs workflows. It:
// 1. Receives a workflow ID from the BullMQ queue
// 2. Loads the workflow (nodes + edges) from the database
// 3. Topologically sorts the nodes (respecting DAG order)
// 4. Executes each node in sequence, passing output to the next
// 5. Tracks status and emits real-time updates via Socket.IO
//
// WHAT IS TOPOLOGICAL SORT?
// In a DAG (Directed Acyclic Graph), nodes must run in dependency order.
// If Node A → Node B → Node C, then A runs first, then B, then C.
// Topological sort figures out this order automatically.

import { Queue, Worker, Job } from 'bullmq';
import { prisma } from '../lib/prisma';
import { executeNode, NodeExecutionInput } from '../services/nodeExecutor';
import { emitExecutionStatus, emitNodeStatus, emitExecutionLog } from '../lib/socketio';
import { decryptData } from '../utils/encryption';
import { logger } from '../utils/logger';

const REDIS_URL = process.env.REDIS_URL || 'redis://localhost:6379';

// Parse Redis URL into connection options
function getRedisConnection() {
  const url = new URL(REDIS_URL);
  return {
    host: url.hostname,
    port: parseInt(url.port) || 6379,
    password: url.password || undefined,
    username: url.username || undefined,
    tls: url.protocol === 'rediss:' ? {} : undefined,
  };
}

// ---- BullMQ Queue ----
// Jobs are added to this queue when a user clicks "Run"
export const workflowQueue = new Queue('workflow-execution', {
  connection: getRedisConnection(),
  defaultJobOptions: {
    removeOnComplete: 100, // Keep last 100 completed jobs
    removeOnFail: 50,
    attempts: 3, // Retry failed jobs 3 times
    backoff: {
      type: 'exponential',
      delay: 5000,
    },
  },
});

// ---- Cron Job Management ----
export async function registerCronJob(workflowId: string, cronExpression: string) {
  await unregisterCronJob(workflowId);
  await workflowQueue.add(
    'execute-cron',
    { workflowId, isCron: true },
    {
      repeat: { pattern: cronExpression },
      jobId: `cron-${workflowId}`,
    }
  );
  logger.info(`⏰ Registered cron job for workflow ${workflowId} with pattern: ${cronExpression}`);
}

export async function unregisterCronJob(workflowId: string) {
  const repeatableJobs = await workflowQueue.getRepeatableJobs();
  const job = repeatableJobs.find((j) => j.id === `cron-${workflowId}`);
  if (job) {
    await workflowQueue.removeRepeatableByKey(job.key);
    logger.info(`⏰ Unregistered cron job for workflow ${workflowId}`);
  }
}

// ---- Interfaces ----
interface FlowNode {
  id: string;
  type: string;
  data: {
    nodeType: string;
    label: string;
    config: Record<string, unknown>;
  };
  position: { x: number; y: number };
}

interface FlowEdge {
  id: string;
  source: string;
  target: string;
  sourceHandle?: string | null;
}

// ---- Topological Sort ----
// Determines the execution order of nodes based on edges
function topologicalSort(nodes: FlowNode[], edges: FlowEdge[]): FlowNode[] {
  const nodeMap = new Map(nodes.map((n) => [n.id, n]));
  const inDegree = new Map<string, number>();
  const adjacency = new Map<string, string[]>();

  // Initialize
  for (const node of nodes) {
    inDegree.set(node.id, 0);
    adjacency.set(node.id, []);
  }

  // Count incoming edges for each node
  for (const edge of edges) {
    const count = inDegree.get(edge.target) || 0;
    inDegree.set(edge.target, count + 1);
    const adj = adjacency.get(edge.source) || [];
    adj.push(edge.target);
    adjacency.set(edge.source, adj);
  }

  // Start with nodes that have no incoming edges (in-degree 0)
  const queue: string[] = [];
  for (const [nodeId, degree] of inDegree) {
    if (degree === 0) queue.push(nodeId);
  }

  const sorted: FlowNode[] = [];
  while (queue.length > 0) {
    const nodeId = queue.shift()!;
    const node = nodeMap.get(nodeId);
    if (node) sorted.push(node);

    const neighbors = adjacency.get(nodeId) || [];
    for (const neighbor of neighbors) {
      const newDegree = (inDegree.get(neighbor) || 1) - 1;
      inDegree.set(neighbor, newDegree);
      if (newDegree === 0) queue.push(neighbor);
    }
  }

  return sorted;
}

// ---- BullMQ Worker ----
// Processes workflow execution jobs
export function startWorkflowWorker() {
  const worker = new Worker(
    'workflow-execution',
    async (job: Job) => {
      let { workflowId, executionId } = job.data;
      const { isCron, triggerPayload } = job.data;

      if (!executionId && isCron) {
        // Generated by repeatable cron job, create execution record now
        const execution = await prisma.execution.create({
          data: {
            workflowId,
            status: 'PENDING',
            triggeredBy: 'CRON',
          },
        });
        executionId = execution.id;
      }

      logger.info(`🚀 Starting execution ${executionId} for workflow ${workflowId}`);
      emitExecutionStatus(executionId, 'RUNNING');
      emitExecutionLog(executionId, 'info', '🚀 Workflow execution started');

      try {
        // 1. Load the workflow from the database
        const workflow = await prisma.workflow.findUnique({
          where: { id: workflowId },
        });

        if (!workflow) {
          throw new Error(`Workflow ${workflowId} not found`);
        }

        const nodes = (workflow.nodesJson as unknown as FlowNode[]) || [];
        const edges = (workflow.edgesJson as unknown as FlowEdge[]) || [];

        if (nodes.length === 0) {
          throw new Error('Workflow has no nodes to execute');
        }

        // 2. Topologically sort the nodes
        const sortedNodes = topologicalSort(nodes, edges);
        emitExecutionLog(
          executionId,
          'info',
          `📋 Execution plan: ${sortedNodes.map((n) => n.data.label).join(' → ')}`,
        );

        // 3. Execute each node in order
        const nodeOutputs = new Map<string, any>();
        const skippedNodes = new Set<string>();
        let hasFailure = false;

        // Update execution with total node count
        await prisma.execution.update({
          where: { id: executionId },
          data: { status: 'RUNNING' },
        });

        for (const node of sortedNodes) {
          // Mark node as RUNNING
          emitNodeStatus(executionId, node.id, 'RUNNING');
          emitExecutionLog(executionId, 'info', `▶️ Running: ${node.data.label}`, node.id);

          // Create node execution record
          const nodeExecution = await prisma.nodeExecution.create({
            data: {
              executionId,
              nodeId: node.id,
              nodeType: node.data.nodeType,
              nodeName: node.data.label,
              status: 'RUNNING',
              startedAt: new Date(),
            },
          });

          // Find the previous node's output (follow edges)
          const incomingEdge = edges.find((e) => e.target === node.id);
          
          let shouldSkip = false;
          let previousOutput: any = triggerPayload || null;

          if (incomingEdge) {
            const parentId = incomingEdge.source;
            // 1. If parent was skipped, we are automatically skipped
            if (skippedNodes.has(parentId)) {
              shouldSkip = true;
            } else {
              // 2. If parent was a router/condition, verify branch matches handle
              const parentOutput = nodeOutputs.get(parentId);
              if (parentOutput && typeof parentOutput === 'object' && 'branch' in parentOutput) {
                // The parent chose a specific branch. If this edge isn't on that branch, skip!
                if (incomingEdge.sourceHandle !== parentOutput.branch) {
                  shouldSkip = true;
                }
              }
              // Normal data passing (if parent returned passedData specifically, use it, else whole output)
              previousOutput = parentOutput && typeof parentOutput === 'object' && 'passedData' in parentOutput
                ? parentOutput.passedData
                : parentOutput;
            }
          }

          if (shouldSkip) {
            skippedNodes.add(node.id);
            emitExecutionLog(executionId, 'info', `⏭️ Skipped: ${node.data.label} (Condition not met or parent skipped)`, node.id);
            // Optionally record as SKIPPED in db
            await prisma.nodeExecution.create({
              data: {
                executionId,
                nodeId: node.id,
                nodeType: node.data.nodeType,
                nodeName: node.data.label,
                status: 'SKIPPED' as any, // If DB schema allows it, else use SUCCESS/IGNORED
                startedAt: new Date(),
                completedAt: new Date(),
                duration: 0,
              },
            }).catch(() => {}); // ignore enum failure if SKIPPED not in schema
            continue;
          }

          // Fetch and decrypt credentials if specified
          let credentials: Record<string, string> | undefined = undefined;
          const credentialId = node.data.config?.credentialId as string | undefined;

          if (credentialId) {
            try {
              const cred = await prisma.credential.findUnique({
                where: { id: credentialId },
              });
              if (cred) {
                const decryptedStr = decryptData(cred.encryptedData);
                credentials = JSON.parse(decryptedStr);
                emitExecutionLog(executionId, 'info', `🔑 Injected stored credentials`, node.id);
              } else {
                emitExecutionLog(executionId, 'warn', `⚠️ Credential ID ${credentialId} not found in database`, node.id);
              }
            } catch (err) {
              const errMsg = err instanceof Error ? err.message : String(err);
              logger.error(`Failed to decrypt credentials for node ${node.id}: ${errMsg}`);
              emitExecutionLog(executionId, 'warn', `⚠️ Failed to decrypt credentials: ${errMsg}`, node.id);
            }
          }

          // Execute the node
          const input: NodeExecutionInput = {
            nodeId: node.id,
            nodeType: node.data.nodeType,
            label: node.data.label,
            config: node.data.config || {},
            previousOutput,
            credentials,
          };

          const result = await executeNode(input);

          // Store the output
          nodeOutputs.set(node.id, result.output);

          // Update node execution record
          await prisma.nodeExecution.update({
            where: { id: nodeExecution.id },
            data: {
              status: result.success ? 'SUCCESS' : 'FAILED',
              outputData: result.output as object || undefined,
              errorMessage: result.error || undefined,
              duration: result.duration,
              completedAt: new Date(),
            },
          });

          if (result.success) {
            emitNodeStatus(executionId, node.id, 'COMPLETED', {
              duration: result.duration,
            });
            emitExecutionLog(
              executionId,
              'success',
              `✅ Completed: ${node.data.label} (${result.duration}ms)`,
              node.id,
            );
          } else {
            emitNodeStatus(executionId, node.id, 'FAILED', {
              error: result.error,
            });
            emitExecutionLog(
              executionId,
              'error',
              `❌ Failed: ${node.data.label} — ${result.error}`,
              node.id,
            );
            hasFailure = true;
            break; // Stop execution on failure
          }
        }

        // 4. Mark execution as completed or failed
        const finalStatus = hasFailure ? 'FAILED' : 'COMPLETED';
        await prisma.execution.update({
          where: { id: executionId },
          data: {
            status: finalStatus,
            completedAt: new Date(),
          },
        });

        emitExecutionStatus(executionId, finalStatus);
        emitExecutionLog(
          executionId,
          hasFailure ? 'error' : 'success',
          hasFailure ? '❌ Workflow execution failed' : '🎉 Workflow execution completed!',
        );

        logger.success(`✅ Execution ${executionId} ${finalStatus}`);
      } catch (error) {
        const errorMsg = error instanceof Error ? error.message : 'Unknown error';
        logger.error(`❌ Execution ${executionId} failed: ${errorMsg}`);

        await prisma.execution.update({
          where: { id: executionId },
          data: {
            status: 'FAILED',
            completedAt: new Date(),
          },
        });

        emitExecutionStatus(executionId, 'FAILED', { error: errorMsg });
        emitExecutionLog(executionId, 'error', `❌ Fatal error: ${errorMsg}`);
      }
    },
    {
      connection: getRedisConnection(),
      concurrency: 5, // Run up to 5 workflows simultaneously
      lockDuration: 60000, // Give each node 60s to finish before assuming worker crashed
    },
  );

  worker.on('completed', (job) => {
    logger.info(`📦 Job ${job.id} completed`);
  });

  worker.on('failed', (job, error) => {
    logger.error(`📦 Job ${job?.id} failed: ${error.message}`);
  });

  logger.success('🏭 Workflow execution worker started');
  return worker;
}
